# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=15)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_id', models.CharField(max_length=200)),
                ('lugar_ds', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(max_length=200)),
                ('option_code', models.CharField(max_length=200)),
                ('option_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='localizacion',
            name='option_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.Option'),
        ),
        migrations.AddField(
            model_name='coordenadas',
            name='local_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.Localizacion'),
        ),
    ]
