# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localizacion',
            name='option_ref',
        ),
    ]
